/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import Slideshow from 'react-native-image-slider-show';


const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Slideshow 
      dataSource={[
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
        { url:require('./img/example-01.jpg') },
        { url:require('./img/example-02.jpg') },
        { url:require('./img/example-03.jpg') },
        { url:require('./img/example-04.jpg') },
        { url:require('./img/example-05.jpg') },
        { url:require('./img/example-06.jpg') },
        { url:require('./img/example-07.jpg') },
        { url:require('./img/example-08.jpg') },
        { url:require('./img/example-09.jpg') },
        { url:require('./img/example-10.jpg') },
        { url:require('./img/example-11.jpg') },
        { url:require('./img/example-12.jpg') },
    ]}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
